wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668647719.088289
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.3
      8:
      - 5
architecture:
  desc: null
  value: VSGN
batch_size:
  desc: null
  value: 11
dataset:
  desc: null
  value: ego4d
learning_rate:
  desc: null
  value: 0.0001
num_epoch:
  desc: null
  value: 30
optimizer_name:
  desc: null
  value: Adam
use_ViT:
  desc: null
  value: false
use_xGPN:
  desc: null
  value: true
